---
- block:

    - name: Query Tower for existing organizations and credentials
      include_tasks: query_tower.yml

    - name: 'Add new inventory organizations'
      include_tasks: process-organization.yml
      with_items:
        - '{{ ansible_tower.organizations }}'
      loop_control:
        loop_var: organization

    - name: Re-query Tower for newly added organizations and credentials
      include_tasks: query_tower.yml

    - name: 'Update existing inventory organizations'
      include_tasks: process-organization.yml
      with_items:
        - '{{ ansible_tower.organizations }}'
      loop_control:
        loop_var: organization

  when:
    - ansible_tower.organizations is defined
