---
- block:

    - name: 'Get the existing organizations'
      rest_get:
        host_url: '{{ ansible_tower.url | default(default_ansible_tower_url) }}'
        rest_user: '{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}'
        rest_password: '{{ ansible_tower.admin_password }}'
        api_uri: '/api/v2/organizations/'
      register: existing_organizations_output

    - name: 'Get the existing credentials'
      rest_get:
        host_url: '{{ ansible_tower.url | default(default_ansible_tower_url) }}'
        rest_user: '{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}'
        rest_password: '{{ ansible_tower.admin_password }}'
        api_uri: '/api/v2/credentials/'
      register: existing_credentials_output
